# Generated by Django 2.0.4 on 2018-04-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('normal', 'Normal'), ('specific', 'Specific'), ('gold', 'Gold')], default='normal', max_length=8),
        ),
    ]
