# Generated by Django 2.0.4 on 2018-04-23 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_slider'),
        ('users', '0002_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpgradeRequest',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Base')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male')], default='male', max_length=6)),
                ('active_flag', models.BooleanField(default=False)),
                ('upgrade_request_related_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_request_related_user_name', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('base.base',),
        ),
    ]
