# Generated by Django 2.0.4 on 2018-04-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_upgraderequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upgraderequest',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male')], max_length=6),
        ),
    ]
