# Generated by Django 2.0.4 on 2018-05-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180423_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgraderequest',
            name='type',
            field=models.CharField(choices=[('normal', 'Normal'), ('specific', 'Specific'), ('gold', 'Gold')], default='specific', max_length=8),
        ),
    ]
