# Generated by Django 2.0.4 on 2018-05-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_upgraderequest_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upgraderequest',
            name='active_flag',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='upgraderequest',
            name='first_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='upgraderequest',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male')], db_index=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='upgraderequest',
            name='last_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='upgraderequest',
            name='type',
            field=models.CharField(choices=[('normal', 'Normal'), ('specific', 'Specific'), ('gold', 'Gold')], db_index=True, default='specific', max_length=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male')], db_index=True, default='male', max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('normal', 'Normal'), ('specific', 'Specific'), ('gold', 'Gold')], db_index=True, default='normal', max_length=8),
        ),
    ]
