# Generated by Django 2.0.4 on 2018-05-17 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20180517_0935'),
        ('users', '0006_auto_20180517_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='FCMToken',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Base')),
                ('token', models.CharField(max_length=256)),
                ('fcm_token_related_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_token_related_user_name', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('base.base',),
        ),
    ]
