# Generated by Django 2.0.4 on 2018-04-18 12:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_time', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now)),
                ('delete_flag', models.BooleanField(db_index=True, default=False, help_text='Boolean')),
            ],
            options={
                'verbose_name_plural': 'Basics',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Base')),
                ('text', models.TextField()),
            ],
            bases=('base.base',),
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Base')),
                ('discount_value', models.IntegerField()),
            ],
            bases=('base.base',),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Base')),
            ],
            bases=('base.base',),
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Base')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            bases=('base.base',),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Base')),
                ('report_text', models.TextField(blank=True, null=True)),
            ],
            bases=('base.base',),
        ),
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Base')),
                ('phone_number', models.CharField(max_length=11)),
                ('code', models.CharField(max_length=5)),
            ],
            bases=('base.base',),
        ),
        migrations.AddField(
            model_name='report',
            name='report_related_parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_related_parent_name', to='base.Base'),
        ),
    ]
