# Generated by Django 2.0.4 on 2018-04-12 10:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_time', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now)),
                ('delete_flag', models.BooleanField(db_index=True, default=False, help_text='Boolean')),
            ],
            options={
                'verbose_name_plural': 'Basics',
                'ordering': ['-pk'],
            },
        ),
    ]
