# Generated by Django 2.0.4 on 2018-04-15 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Base')),
                ('phone_number', models.CharField(max_length=11)),
                ('code', models.CharField(max_length=5)),
            ],
            bases=('base.base',),
        ),
    ]
