# Generated by Django 2.0.4 on 2018-04-22 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20180418_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_related_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_related_parent_name', to='base.Base'),
        ),
    ]
