# Generated by Django 2.0.4 on 2018-04-16 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Base')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rate_related_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_related_parent_name', to='base.Base')),
                ('rate_related_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_related_user_name', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('base.base',),
        ),
    ]
