# Generated by Django 2.0.4 on 2018-04-22 11:05

import base.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_auto_20180422_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Base')),
                ('file_path', models.FileField(upload_to=base.models.get_upload_path)),
                ('file_related_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_related_parent_name', to='base.Base')),
                ('file_related_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_related_user_name', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('base.base',),
        ),
    ]
