# Generated by Django 2.0.4 on 2018-04-17 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Base')),
                ('discount_value', models.IntegerField()),
            ],
            bases=('base.base',),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Base')),
                ('favorite_related_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_related_parent_name', to='base.Base')),
                ('favorite_related_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_related_user_name', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('base.base',),
        ),
        migrations.AddField(
            model_name='discount',
            name='discount_related_parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_related_parent_name', to='base.Base'),
        ),
    ]
