# Generated by Django 2.0.4 on 2018-04-17 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0005_auto_20180417_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Base')),
                ('report_text', models.TextField(blank=True, null=True)),
                ('report_related_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_related_parent_name', to='base.Base')),
                ('report_related_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_related_user_name', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('base.base',),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='related_parent',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_related_parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comment_related_parent_name', to='base.Base'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_related_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comment_related_user_name', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discount',
            name='discount_related_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='discount_related_user_name', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
