# Generated by Django 2.0.4 on 2018-04-25 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_viewmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopFilter',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Base')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('link', models.CharField(max_length=200)),
                ('order', models.IntegerField()),
            ],
            bases=('base.base',),
        ),
    ]
