# Generated by Django 2.0.4 on 2018-05-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_base_related_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='active_flag',
            field=models.BooleanField(default=True),
        ),
    ]
