# Generated by Django 2.0.4 on 2018-05-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_comment_active_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='rate_average',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
