# Generated by Django 2.0.4 on 2018-05-17 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20180517_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='active_flag',
        ),
    ]
