# Generated by Django 2.0.4 on 2018-05-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_comment_active_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='active_flag',
            field=models.BooleanField(db_index=True, default=False, help_text='Boolean'),
        ),
    ]
