# Generated by Django 2.0.4 on 2018-06-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_base_active_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='updated_by_user',
            field=models.BooleanField(db_index=True, default=True, help_text='Boolean'),
        ),
    ]
