# Generated by Django 2.0.4 on 2018-04-18 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storevisit',
            name='store_visit_related_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_visit_related_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='store',
            name='store_related_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_related_category_name', to='stores.StoreCategory'),
        ),
        migrations.AddField(
            model_name='store',
            name='store_related_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_related_owner_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='store',
            name='store_related_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_related_user_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
