# Generated by Django 2.0.4 on 2018-04-16 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0002_store_related_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreVisit',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Base')),
                ('store_visit_related_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_visit_related_store', to='stores.Store')),
                ('store_visit_related_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_visit_related_user', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('base.base',),
        ),
    ]
