# Generated by Django 2.0.4 on 2018-04-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_store_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='storevisit',
            name='active_flag',
            field=models.BooleanField(default=False),
        ),
    ]
