# Generated by Django 2.0.4 on 2018-04-17 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0003_storevisit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='related_category',
        ),
        migrations.RemoveField(
            model_name='store',
            name='related_owner',
        ),
        migrations.AddField(
            model_name='store',
            name='store_related_category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='store_related_category_name', to='stores.StoreCategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='store_related_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_related_owner_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='store',
            name='store_related_user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='store_related_user_name', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
