# Generated by Django 2.0.4 on 2018-05-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_storevisit_active_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='active_flag',
            field=models.BooleanField(default=False),
        ),
    ]
