# Generated by Django 2.0.4 on 2018-05-17 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_auto_20180517_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='active_flag',
        ),
        migrations.RemoveField(
            model_name='storevisit',
            name='active_flag',
        ),
    ]
