# Generated by Django 2.0.4 on 2018-04-24 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0005_slider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Base')),
                ('title', models.CharField(max_length=100)),
                ('made_in_iran', models.BooleanField()),
            ],
            bases=('base.base',),
        ),
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Base')),
                ('title', models.CharField(max_length=100)),
                ('product_brand_related_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_brand_related_user_name', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('base.base',),
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Base')),
                ('title', models.CharField(max_length=100)),
                ('product_category_related_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_category_related_parent_name', to='products.ProductCategory')),
                ('product_category_related_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category_related_user_name', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('base.base',),
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Base')),
                ('amount', models.IntegerField()),
                ('product_price_related_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_price_related_product_name', to='products.Product')),
            ],
            bases=('base.base',),
        ),
        migrations.AddField(
            model_name='product',
            name='product_related_brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_related_brand_name', to='products.ProductBrand'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_related_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_related_category_name', to='products.ProductCategory'),
        ),
    ]
