# Generated by Django 2.0.4 on 2018-04-24 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_product_product_related_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_related_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_related_user_name', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_related_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_related_store_name', to='stores.Store'),
        ),
    ]
