# Generated by Django 2.0.4 on 2018-04-24 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_store_address'),
        ('products', '0004_auto_20180424_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='product_brand_related_store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_brand_related_store_name', to='stores.Store'),
            preserve_default=False,
        ),
    ]
