# Generated by Django 2.0.4 on 2018-04-24 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_productbrand_product_brand_related_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprice',
            name='product_price_related_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_price_related_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
