# Generated by Django 2.0.4 on 2018-04-26 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_storevisit_active_flag'),
        ('products', '0006_productprice_product_price_related_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='product_category_related_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_category_related_store_name', to='stores.Store'),
        ),
    ]
