# Generated by Django 2.0.4 on 2018-04-26 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productcategory_product_category_related_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='product_category_related_store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_category_related_store_name', to='stores.Store'),
            preserve_default=False,
        ),
    ]
