# Generated by Django 2.0.4 on 2018-05-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20180517_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
