# Generated by Django 2.0.4 on 2018-05-17 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productbrand_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='active_flag',
        ),
    ]
