# Generated by Django 2.0.4 on 2018-05-22 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_base_active_flag'),
        ('products', '0013_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOffer',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Base')),
                ('reason', models.TextField()),
                ('start_date', models.IntegerField(db_index=True)),
                ('end_date', models.IntegerField(db_index=True)),
                ('product_offer_related_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_offer_related_product_name', to='products.Product')),
            ],
            bases=('base.base',),
        ),
    ]
